title: FutureBot - A SumoBot for STEM
email: marcelo.jara@pucp.edu.pe
description: >- # this means to ignore newlines until "baseurl:"
  FutureBot is a STEM project to learn and have fun. There is no 
  minimum age, so whether you are 10 or 20 years old, you can 
  get to work and create your robot. Finally, don't forget that 
  "The best way to predict the future is to make it."  
#baseurl: "FutureBot-MiniSumoBot" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: MarceloFuture
github_username:  MarceJara

# Build settings
#theme: minima
#theme: just-the-docs
#theme: jekyll-text-theme
#remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
 # - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
